### ISSUE TITLE
objeto 3d

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-project-ra#1]
[Objeto 2D y 3D.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-project-ra/files/11104395/Objeto.2D.y.3D.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by CxrlosMX** [comment]
Buen trabajo: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
